

name: Deploy to Azure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: 'terraform/**'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  WORKING_DIR: ./terraform/infrastruktur

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Hent variabler
        uses: actions/download-artifact@v4
        with:
          name: variables

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "^1.3.7"
          terraform_wrapper: false
      
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: ${{ env.WORKING_DIR }}
      
      - name: Terraform apply prod
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

      - name: Login to Azure
        run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

      - name: Find and Update All Student Containers
        run: |
        # Find all student containers
        CONTAINERS=$(az containerapp list --query "[].{name:name, resourceGroup:resourceGroup}" --output tsv)

        if [ -z "$CONTAINERS" ]; then
        echo "Ingen student container apps funnet!"
        exit 1
        fi

        while read -r APP_NAME RESOURCE_GROUP; do
        echo "Sjekker container: $APP_NAME in resource group: $RESOURCE_GROUP"

        # Updating student containers
        if [[ "$APP_NAME" == *"-"* ]]; then
        echo "Oppdaterer container: $APP_NAME"
        az containerapp update \
        --name $APP_NAME \
        --resource-group $RESOURCE_GROUP \
        --image ghcr.io/bachelorgruppe117-ntnu-gjovik/$APP_NAME:latest
        fi
        done <<< "$CONTAINERS"


