name: Build terraform code
# Bli calla av byggDocker
# test2

# Controls when the workflow will run
on:
  

#  workflow_run:
#    workflows: ["Build Docker"]
#    types:
#      - completed

  workflow_call:



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  WORKING_DIR: ./

jobs:
  # Appender terraformkode for studentoppgave
  buildTerraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Hent variabler
        uses: actions/download-artifact@v4
        with:
          name: variables

      - shell: bash
        run: |
          FOLDER_NAME="$(cat studentFolderName.txt)"
          echo "STUDENT_FOLDER=$FOLDER_NAME" >> $GITHUB_ENV
          IMAGE_NAME="$(cat imageName.txt)"
          echo "DOCKER_IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV


      - name: Get config
        id: config
        run: |
          config="./studentOppgaver/${{env.STUDENT_FOLDER}}/config.txt"

        # avvent mappestruktur i terraform
      - name: Append container
        id: appendContainer
        
        run: |
          echo "//Container for ${{env.STUDENT_FOLDER}}" >> ./terraform/infrastruktur/deployments/main.tf
          sudo chmod 755 ./terraform/scripts/addContainer.sh
          ./terraform/scripts/addContainer.sh ${{env.STUDENT_FOLDER}} >> ./terraform/infrastruktur/modules/containers/main.tf

      - name: Append variabeldefenisjoner
        id: appendVarDef
        run: |
          echo "//Variabler for ${{env.STUDENT_FOLDER}}" >> ./terraform/infrastruktur/modules/variables.tf
          sudo chmod 755 ./terraform/scripts/addVariables.sh
          ./terraform/scripts/addVariables.sh ${{env.STUDENT_FOLDER}} >> ./terraform/infrastruktur/modules/containers/variables.tf

      - name: Append variabelverdier
        id: appendVarVal
        run: |
          echo "//Variabelverdier for ${{env.STUDENT_FOLDER}}" >> ./terraform/infrastruktur/deployments/terraformProd.tfvars
          cat $config >> ./terraform/infrastruktur/deployments/terraform.tfvars
 #         cat ${{env.DOCKER_IMAGE_NAME}} >> ./terraform/terraform.tfvars

      - name: Push commit
        id: pushCommit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "workflow la til ${{env.STUDENT_FOLDER}}"
          git push origin databasewf