name: Build terraform code
# Bli calla av byggDocker
# test2

# Controls when the workflow will run
on:
  

#  workflow_run:
#    workflows: ["Build Docker"]
#    types:
#      - completed

  workflow_call:



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  PA_TOKEN: ${{ secrets.PA_TOKEN}}
  WORKING_DIR: ./

jobs:
  # Appender terraformkode for studentoppgave
  buildTerraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Hent variabler
        uses: actions/download-artifact@v4
        with:
          name: variables

      - shell: bash
        run: |
          FOLDER_NAME="$(cat studentFolderName.txt)"
          echo "STUDENT_FOLDER=$FOLDER_NAME" >> $GITHUB_ENV
          IMAGE_NAME="$(cat imageName.txt)"
          echo "DOCKER_IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo -n ${{env.STUDENT_FOLDER}} >> ./terraform/oppgaver.txt
          echo -e "\t${{env.DOCKER_IMAGE_NAME}}" >> ./terraform/oppgaver.txt


      - name: Get config
        id: config
        run: |
          config="./studentOppgaver/${{env.STUDENT_FOLDER}}/config.txt"

      - name: sjekk database
        id: database
        run: |
          if [[ -e ./studentOppgaver/${{env.STUDENT_FOLDER}}/database ]]; then DATABASE=true >> $GITHUB_ENV; 
          else DATABASE=false >> $GITHUB_ENV; fi

      # Add database
      - name: Append database
        id: appendDatabase
        if: ${{env.DATABASE}} == true
        run: |
          echo "postdb = {" >> ./terraform/infrastruktur/terraform.tfvars
          for line in $(awk '{print $1}' ./terraform/oppgaver.txt); do
          echo "$line = {name = $line}" >> ./terraform/infrastruktur/terraform.tfvars
          done
          echo "}" >> ./terraform/infrastruktur/terraform.tfvars


    
      # Add resource group
      - name: Append variables for resource group
        id: appendRGVariables
        run: |
          echo "rg_dynamic = {" >> ./terraform/infrastruktur/terraform.tfvars
          for line in $(cat /terraform/oppgaver.txt); do
            name=$(echo $line | awk '{print $1}')
            echo "$name = {name = rg-$name location="westeurope"}" >> ./terraform/infrastruktur/terraform.tfvars
          done
          echo "}" >> ./terraform/infrastruktur/terraform.tfvars
        
      # Add container
      - name: Append variables for container
        id: appendContainerVariables
        run: |
          echo "container = {" >> ./terraform/infrastruktur/terraform.tfvars
          for line in $(cat /terraform/oppgaver.txt); do
            name=$(echo $line | awk '{print $1}')
            image=$(echo $line | awk '{print $2}')
            echo "$name = {name = $name image=$image" >> ./terraform/infrastruktur/terraform.tfvars
          done
          echo "}" >> ./terraform/infrastruktur/terraform.tfvars

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraformVars
          path: |
            ./terraform/infrastruktur/terraform.tfvars
         
     

      - name: Push commit
        id: pushCommit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "workflow la til ${{env.STUDENT_FOLDER}}"
          git push origin databasewf