name: Build terraform code
# Bli calla av byggDocker
# test2

# Controls when the workflow will run
on:
  

#  workflow_run:
#    workflows: ["Build Docker"]
#    types:
#      - completed

  workflow_call:



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  PA_TOKEN: ${{ secrets.PA_TOKEN}}
  WORKING_DIR: ./

jobs:
  # Appender terraformkode for studentoppgave
  buildTerraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Hent variabler
        uses: actions/download-artifact@v4
        with:
          name: variables

   
        


      - name: Get config
        id: config
        run: |
          config="./studentOppgaver/${{env.STUDENT_FOLDER}}/config.txt"

      - name: sjekk database
        id: database
        run: |
          if [[ -e ./studentOppgaver/${{env.STUDENT_FOLDER}}/database ]]; then 
            echo "DATABASE=true" >> $GITHUB_ENV; 
          else 
            echo "DATABASE=false" >> $GITHUB_ENV; fi

      # Add database
      - name: Append database
        id: appendDatabase
        if: ${{env.DATABASE}} == true
        run: |
          echo "postdb = {" >> ./terraform/infrastruktur/terraform.tfvars
          for line in $(awk '{print $1}' ./terraform/oppgaver.txt); do
          echo -e "\t$line = {name = $line}" >> ./terraform/infrastruktur/terraform.tfvars
          done
          echo "}" >> ./terraform/infrastruktur/terraform.tfvars


    
      # Add resource group
      - name: Append variables for resource group
        id: appendRGVariables
        run: |
          echo "rg_dynamic = {" >> ./terraform/infrastruktur/terraform.tfvars
          while IFS= read -r line; do
            echo "$line"
            name=$(echo "$line" | awk '{print $1}')
            echo -e "\t$name = {name = \"$name\"\n\tlocation = \"westeurope\"}" >> ./terraform/infrastruktur/terraform.tfvars
          done < oppgaver.txt
          echo "}" >> ./terraform/infrastruktur/terraform.tfvars
        
      # Add container
      - name: Append variables for container
        id: appendContainerVariables
        run: |
          echo "container = {" >> ./terraform/infrastruktur/terraform.tfvars
          while IFS= read -r line; do
            echo "$line"
            name=$(echo $line | awk '{print $1}')
            image=$(echo $line | awk '{print $2}')
            echo -e "\t$name = {name = \"$name\"\n\timage=\"$image\"}" >> ./terraform/infrastruktur/terraform.tfvars
          done < oppgaver.txt
          echo "}" >> ./terraform/infrastruktur/terraform.tfvars

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraformVars
          path: |
            ./terraform/infrastruktur/terraform.tfvars
         
     

      - name: Push commit
        id: pushCommit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "workflow la til ${{env.STUDENT_FOLDER}}"
          git push origin databasewf