name: Build and Push Student Submission

on:
  push:
    paths:
      - 'studentOppgaver/**'  # Runs only when something changes inside studentOppgaver/

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Get Latest Commit Message
      - name: Get Commit Message
        id: commit_message
        run: echo "MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      # Step 3: Extract Folder Name from Commit Message
      - name: Extract Folder Name
        id: extract_folder
        run: |
          if [[ "${{ env.MESSAGE }}" =~ ny\ studentoppgave\ ([a-zA-Z0-9_-]+) ]]; then
            FOLDER_NAME=${BASH_REMATCH[1]}
            echo "STUDENT_FOLDER=$FOLDER_NAME" >> $GITHUB_ENV
            echo "Processing folder: $FOLDER_NAME"
          else
            echo "Commit message does not specify a student folder. Exiting."
            exit 1
          fi

      # Step 4: Log in to GitHub Container Registry (GHCR)
      - name: Docker Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          SUBMISSION_DIR="studentOppgaver/${{ env.STUDENT_FOLDER }}"
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ env.STUDENT_FOLDER }}-app:latest"

          echo "Building Docker image: $IMAGE_NAME from $SUBMISSION_DIR"
          docker build -t "$IMAGE_NAME" "$SUBMISSION_DIR"

          echo "Pushing Docker image: $IMAGE_NAME"
          docker push "$IMAGE_NAME"
