name: Build and Push Student Submission

on:
  push:
    paths:
      - 'studentOppgaver/**'  # Runs only when something changes inside studentOppgaver/
  
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Runs only if commit contains "ny studentoppgave"
    if: contains(github.event.head_commit.message, 'ny studentoppgave') 
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Extract Folder Name from Commit Message (Preserve Original Case)
      - name: Extract Folder Name
        id: extract_folder
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ny\ studentoppgave\ ([a-zA-Z0-9_-]+) ]]; then
            FOLDER_NAME=${BASH_REMATCH[1]}
            echo "STUDENT_FOLDER=$FOLDER_NAME" >> $GITHUB_ENV
            echo "Processing folder: $FOLDER_NAME"
          else
            echo "Commit message does not specify a student folder. Exiting."
            exit 1
          fi

      # Step 3: Convert GitHub Repository Owner to Lowercase (For Docker Naming)
      - name: Convert Repo Owner to Lowercase
        run: echo "REPO_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 4: Convert Folder Name to Lowercase ONLY for Docker Image Name
      - name: Set Docker Image Name
        run: |
          echo "DOCKER_IMAGE_NAME=ghcr.io/${{ env.REPO_OWNER }}/$(echo ${{ env.STUDENT_FOLDER }} | tr '[:upper:]' '[:lower:]')-app:latest" >> $GITHUB_ENV
          echo "Docker image name: ${{ env.DOCKER_IMAGE_NAME }}"

      # Step 5: Log in to GitHub Container Registry (GHCR)
      - name: Docker Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ env.REPO_OWNER }}" --password-stdin

      # Step 6: Build and Push Docker Image (Keep Folder Case, Lowercase Image Name)
      - name: Build and Push Docker Image
        run: |
          SUBMISSION_DIR="studentOppgaver/${{ env.STUDENT_FOLDER }}"  # Preserve original case
          
          echo "Building Docker image: ${{ env.DOCKER_IMAGE_NAME }} from $SUBMISSION_DIR"
          docker build -t "${{ env.DOCKER_IMAGE_NAME }}" "$SUBMISSION_DIR"

          echo "Pushing Docker image: ${{ env.DOCKER_IMAGE_NAME }}"
          docker push "${{ env.DOCKER_IMAGE_NAME }}"

      # Upload folder name and image name as artifacts
      - name: Save variables
        run: |
          echo "STUDENT_FOLDER=${{env.STUDENT_FOLDER}} > $GITHUB_ENV" > variables.sh
          echo "DOCKER_IMAGE_NAME=${{env.DOCKER_IMAGE_NAME}} >> $GITHUB_ENV" >> variables.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: variableNames
          path: variables.sh
    
  startWF:
    needs: build-and-push
    uses: Bachelorgruppe117-NTNU-Gjovik/IT-driftsmiljo/.github/workflows/buildTerraform.yml@databasewf
    